### PR TITLE
consistent dockerfiles

### PR DESCRIPTION
**Pull request by praneethmendu**
I made a PR earlier([308](https://github.com/zkopru-network/zkopru/pull/308)) where I got some feedback too, and I made a lot of useless commits trying to apply said feedback and messing with circle CI.

This is just a PR to my main branch with the commits squashed so changes are clear.

### CODE REVIEW

**Comment by wanseob** [comment]
looks much better! Thanks @praneethmendu for your contribution!! @JChanceHud let me merge this PR :)

**Comment by JChanceHud** [comment]
Yep, looks good to me. @praneethmendu make sure to set your editor to automatically trim any trailing whitespace on lines. A couple lines have a trailing space. Not a huge issue, just a good setting to enable.

**Comment by praneethmendu** [comment]
@JChanceHud my bad, new system, thanks for reminding me

**Comment by JChanceHud** [comment]
Hey @praneethmendu could you remove the `.circleci/old_config.yml`?

**Comment by praneethmendu** [comment]
omg, so embarrassing, this was an earlier stash idk how it ended up here. I deleted it now. Is there a simple way to squish these commits or make it cleaner ?

**Comment by wanseob** [comment]
yup sure let me squash and merge this PR

**Pull request merged**
