### PR TITLE
Fix Poseidon deployments

### PR DESCRIPTION
**Pull request by JChanceHud**
Uses the default truffle artifact system for deploying.
Fixes the duplicate contract name problem.
Fixes intermittent error linking Poseidon libraries to other contracts.

### CODE REVIEW

**Comment by wanseob** [comment]
@JChanceHud  I think we need to revert this PR since it doesn't work when we don't have the generated poseidon files in the build artifact directory.

**Comment by JChanceHud** [comment]
@wanseob I'm confused, doesn't the `truffle compile` command create those files?

**Comment by wanseob** [comment]
`truffle compile` generated them before because we've set up the external compiler to generate 3 types of Poseidon hash contracts' binary files. In my case, `cd packages/contracts && yarn test` is emitting a compilation error 🤔

**Comment by JChanceHud** [comment]
Ah, looks like the `truffle-config` in `test-cases` has a reference to the script I removed. I'll fix this and get the tests working.

**Comment by JChanceHud** [comment]
Should be fixed in #151

**Pull request merged**
