### PR TITLE
Test/circuit ci

### PR DESCRIPTION
**Pull request by wanseob**

### CODE REVIEW

**Comment by JChanceHud** [comment]
The machines that run the tests have [2 vCPUs and 4 GB of ram](https://circleci.com/docs/2.0/configuration-reference/#resourceclass). I tried enabling these tests in the past and it took multiple hours to generate the keys.

I think it's good to enable them but we should only run the circuit tests if the circuit files have changed.

**Comment by wanseob** [comment]
> I think it's good to enable them but we should only run the circuit tests if the circuit files have changed.
that makes sense ;)

**Comment by wanseob** [comment]
@JChanceHud updated ;)

**Comment by wanseob** [comment]
I'll merge this since it seems to work well now. This would reduce the testing time a bit :)

**Pull request merged**
